var annotated_dup =
[
    [ "jle", "namespacejle.html", "namespacejle" ],
    [ "Ui", null, [
      [ "WidgetClass", "class_ui_1_1_widget_class.html", null ]
    ] ],
    [ "cgi_env_block", "structcgi__env__block.html", "structcgi__env__block" ],
    [ "char64long16", "unionchar64long16.html", "unionchar64long16" ],
    [ "ctl_msg", "structctl__msg.html", "structctl__msg" ],
    [ "frozen", "structfrozen.html", "structfrozen" ],
    [ "Highlighter", "class_highlighter.html", "class_highlighter" ],
    [ "http_message", "structhttp__message.html", "structhttp__message" ],
    [ "json_token", "structjson__token.html", "structjson__token" ],
    [ "mbuf", "structmbuf.html", "structmbuf" ],
    [ "MD5Context", "struct_m_d5_context.html", "struct_m_d5_context" ],
    [ "ns_add_sock_opts", "structns__add__sock__opts.html", "structns__add__sock__opts" ],
    [ "ns_bind_opts", "structns__bind__opts.html", "structns__bind__opts" ],
    [ "ns_connect_opts", "structns__connect__opts.html", "structns__connect__opts" ],
    [ "ns_connection", "structns__connection.html", "structns__connection" ],
    [ "ns_dns_header", "structns__dns__header.html", "structns__dns__header" ],
    [ "ns_dns_message", "structns__dns__message.html", "structns__dns__message" ],
    [ "ns_dns_resource_record", "structns__dns__resource__record.html", "structns__dns__resource__record" ],
    [ "ns_mgr", "structns__mgr.html", "structns__mgr" ],
    [ "ns_mqtt_message", "structns__mqtt__message.html", "structns__mqtt__message" ],
    [ "ns_mqtt_topic_expression", "structns__mqtt__topic__expression.html", "structns__mqtt__topic__expression" ],
    [ "ns_resolve_async_opts", "structns__resolve__async__opts.html", "structns__resolve__async__opts" ],
    [ "ns_resolve_async_request", "structns__resolve__async__request.html", "structns__resolve__async__request" ],
    [ "ns_rpc_error", "structns__rpc__error.html", "structns__rpc__error" ],
    [ "ns_rpc_reply", "structns__rpc__reply.html", "structns__rpc__reply" ],
    [ "ns_rpc_request", "structns__rpc__request.html", "structns__rpc__request" ],
    [ "ns_send_mqtt_handshake_opts", "structns__send__mqtt__handshake__opts.html", "structns__send__mqtt__handshake__opts" ],
    [ "ns_serve_http_opts", "structns__serve__http__opts.html", "structns__serve__http__opts" ],
    [ "ns_str", "structns__str.html", "structns__str" ],
    [ "proto_data_http", "structproto__data__http.html", "structproto__data__http" ],
    [ "qt_meta_stringdata_Highlighter_t", "structqt__meta__stringdata___highlighter__t.html", "structqt__meta__stringdata___highlighter__t" ],
    [ "qt_meta_stringdata_Widget_t", "structqt__meta__stringdata___widget__t.html", "structqt__meta__stringdata___widget__t" ],
    [ "SHA1_CTX", "struct_s_h_a1___c_t_x.html", "struct_s_h_a1___c_t_x" ],
    [ "socket_address", "unionsocket__address.html", "unionsocket__address" ],
    [ "Ui_WidgetClass", "class_ui___widget_class.html", "class_ui___widget_class" ],
    [ "websocket_message", "structwebsocket__message.html", "structwebsocket__message" ],
    [ "Widget", "class_widget.html", "class_widget" ]
];